### ISSUE TITLE
Excellent work. About the data

### ISSUE THREAD

**Issue by GasaiYU** [yanqinJiang/Animate3D#1]
Congratularions! This is an excellent work! I want to ask will your data be released and if yes when will the data be released. Thanks for your reply!

**Comment by yanqinJiang** [comment]
The data will be released. We're currently preparing the data and the code. Hopefully, it will be released in 2-3 months.

Thanks for your interest in our work!

**Comment by yanqinJiang** [comment]
Training data has been released [here](https://huggingface.co/datasets/yanqinJiang/MV-Video). Welcome to have a try! 😆

**Comment by GasaiYU** [comment]
Cool! Thanks!
