### ISSUE TITLE
the launch.py is missing

### ISSUE THREAD

**Issue by enes3774** [yanqinJiang/Animate3D#2]
Thanks again for that amazing repo. I couldn't find launch.py under animate3D, could you help me?

**Comment by yanqinJiang** [comment]
Sorry I missed launch.py when uploading the files.
[launch.py](https://github.com/yanqinJiang/Animate3D/blob/main/launch.py) is added to the repo now. Please use the latest code and try again.

Thank you for pointing out this issue!
