### ISSUE TITLE
guoyww/animatediff-motion-adapter-v1-5-2 is missing

### ISSUE THREAD

**Issue by hijacks12** [yanqinJiang/Animate3D#4]
![image](https://github.com/user-attachments/assets/ab649ab9-d3b9-44f9-b14a-8e656b5e0d29)
cant find this directory

**Comment by yanqinJiang** [comment]
`motion_adapter_path` points to animatediff's huggingface repo, and the code is supposed to download it automatically when running. The url of this repo is [https://huggingface.co/guoyww/animatediff-motion-adapter-v1-5-2](https://huggingface.co/guoyww/animatediff-motion-adapter-v1-5-2). If your machine cannot get access to huggingface, you can download this model manually and put it under `/path/to/your/animatediff/folder/`, and change `motion_adapter_path` to your local folder.

The same procedure should be followed for the `ip_adapter_path` if you encounter similar access issues.
